apiVersion: v1
kind: ReplicationController
metadata:
  name: myazhar-rc
spec:
   replicas: 3
   selector:
     app: myazharapp
     version: 2.6.2
   template:
     metadata:
       labels:
          app: myazharapp
          version: 2.6.2
     spec:
        containers:
        - name: mynginx
          image: nginx
          ports:
          - containerPort: 80

