apiVersion: v1
kind: ReplicationController
metadata:
   name: myvertexRC
spec:
   replicas: 3
   selector:
    app: myvertexpod
    Version: 2.6.2
template:
   metadata:
   label:
      app: myvertexpod
      Version: 2.6.2
   spec:
      containers:
        -name: mynginx
         image: 
         ports:
           - containerPort: 80