apiVersion: v1
kind: ReplicationController
metadata:
   name: myvertex_rc
spec:
   replicas: 3
   selector:
     app: mynginx
     Version: 2.6.2
   template:
     metadata:
      label:
         app: mynginx
         Version: 2.6.2
   spec:
      containers:
      - name: mynginx_container
        image: nginx
        ports:
            - containerPort: 80 