apiVersion: v1
kind: ReplicationController
metadata:
  name: myazhar-rc
spec:
   replicas: 5
   selector:
     app: myazharapp
     version: 2.6.2
   template:
     metadata:
       labels:
          app: myazharapp
          version: 2.6.2
     spec:
        containers:
        - name: myazharapp-container
          image: shaikhazhar/myjawaimage1:1
          ports:
          - containerPort: 8080

